#!/bin/bash
THEME="$1"
SRC="$HOME/.config/theme-colors/$THEME/css/gtk-colors.css"
DST="$HOME/.config/swaync/colors/colors.css"

[[ -f "$SRC" ]] && cp "$SRC" "$DST" && swaync-client -R && swaync-client -rs
